apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: scalabruhdb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
          - name: MARIADB_DATABASE
            value: scalabruhdb
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password
        # - name: MARIADB_USER
        #   value: superuser
        # - name: MARIADB_PASSWORD
        #   value: superpassword
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: p1-pv-claim