apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-storage-claim
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
