apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rush-hour-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            serviceName: rush-hour-backend
            servicePort: 8088
