apiVersion: v1
kind: Service
metadata:
  name: rush-hour-user
  labels:
    app: rush-hour-user
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: rush-hour-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rush-hour-user
spec:
  selector:
    matchLabels:
      app: rush-hour-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rush-hour-user
    spec:
      containers:
      - image: mariadb:10.8
        name: mariadb
        ports:
        - containerPort: 3306
          name: user-db
        env:
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: pass       
      - image: ghcr.io/big-coconut-team/rush-hour-backend/pfinal-user_svc:latest
        name: rush-hour-user

        ports:
        - containerPort: 8000
        # name: rush-hour-user
      imagePullSecrets:
      - name: rush-hour-dockerconfigjson
