apiVersion: v1
kind: Service
metadata:
  name: user_svc
  labels:
    app: user_svc
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: user_svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-projector-deployment
spec:
  selector:
    matchLabels:
      app: user_svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user_svc
    spec:
      containers:
      - image: mariadb:10.8
        name: mariadb
        ports:
        - containerPort: 3306
          name: user_db
        env:
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: pass       
      - image: ghcr.io/big-coconut-team/rush-hour-backend/pfinal-user_svc:latest
        name: user_svc
        ports:
          - containerPort: 8000
          name: user_svc
      imagePullSecrets:
      - name: secret
